name: CI/CD - Build, Push, Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build & Push Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

      # Build & Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/my-portfolio/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest Docker images..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

            echo "Stopping old containers..."
            docker stop frontend || true && docker rm frontend || true
            docker stop backend || true && docker rm backend || true

            echo "Starting new containers..."
            docker run -d -p 80:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
            docker run -d -p 5000:5000 --name backend ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
